# Generated by Django 6.0.4 on 2026-05-28 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('category', models.CharField(max_length=50)),
                ('time_ago', models.CharField(max_length=50)),
                ('image_alt', models.CharField(default='Crypto graphic', max_length=100)),
                ('content', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Coin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('symbol', models.CharField(max_length=10)),
                ('price', models.FloatField()),
                ('change_24h', models.FloatField()),
                ('market_cap', models.CharField(max_length=50)),
                ('volume_24h', models.CharField(max_length=50)),
                ('circulating_supply', models.CharField(max_length=50)),
                ('max_supply', models.CharField(default='Unlimited', max_length=50)),
                ('rank', models.IntegerField(default=1)),
                ('description', models.TextField()),
                ('sparkline_data', models.CharField(default='[]', max_length=500)),
            ],
        ),
    ]
